### ISSUE TITLE
Есть странная проблема с поведением "изображения"

### ISSUE THREAD

**Issue by i-coder** [developeruz/yii-behaviors#2]
Поведение изображение, при загрузке svg  формат вылетает ошибка именно svg формат
http://joxi.ru/Y2LpqqwSn5YMV2

**Comment by i-coder** [comment]
И еще вопрос, если я делаю запись в админ панели (backend) то во frontend я не получу изображения так как путь абсолютный

**Comment by developeruz** [comment]
Как видно из скриншота, проблема в библиотеке imagine/imagine, т.е баг репорт нужен сюда:  https://github.com/avalanche123/Imagine но т.к imagine использует GD библиотеку, возможно имеет смысл проверить и обновить если нужно ту GD библиотеку, что установлена в вашей сборке php.
