### ISSUE TITLE
Проблема при обновление записи

### ISSUE THREAD

**Issue by i-coder** [developeruz/yii-behaviors#3]
Если сначала загрузить картинку и сохранить запись то все ок но если запись обновить и при этом не выбирать изображение а отправить то старая запись затрется пустой строкой

**Comment by developeruz** [comment]
Скорее всего у вас атрибут модели для картинки (fileAttribute) обозначен как safe и используется в массовом присвоении данных. Сделайте сценарий и уберите этот атрибут из массового присвоения.
